# JVM arguments for Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# Non-transitive R classes
android.nonTransitiveRClass=true

# Enable BuildConfig by default (Required for Retrofit/Network in modern AGP)
android.defaults.buildfeatures.buildConfig=true